spring:
  datasource:
    url: jdbc:postgresql://dpg-cqkb88rqf0us73c6bk00-a.oregon-postgres.render.com/blog_system
    username: test_user
    password: EcQk1IoBvTzGOcprzfYBCCCamm4JvV8E
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    open-in-view: false

env: local
